name: Dev - Kotlin CI/CD with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Build with Gradle (with Test)
        run: |
          echo ${{ secrets.APPLICATION_DEV_YML }} | base64 --decode > ./src/main/resources/application-dev.yml 
          echo ${{ secrets.APPLICATION_YML_DEV_MODE }} | base64 --decode > ./src/main/resources/application.yml
          ./gradlew clean build

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.YOURSSU_STG_HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -

      - name: Deploy to EC2
        run: |
          mv build/libs/soongpt-0.0.1-SNAPSHOT.jar yourssu-soongpt-application.jar
          scp yourssu-soongpt-application.jar ubuntu@${{ secrets.YOURSSU_STG_HOST }}:/ssumgo/soongpt-api
          ssh ubuntu@${{ secrets.YOURSSU_STG_HOST }} "/home/ubuntu/soongpt-api/run.sh"
